name: Hello World!

on:
  push:
    branches:
      - main
      # this is comment

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
